services:
  dev:
    build: .
    volumes:
      - .:/app
      - ./json_key:/app/json_key
    environment:
      - PYTHONPATH=/app/src
      - GOOGLE_APPLICATION_CREDENTIALS=/app/json_key/service_account.json
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    restart: always